[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B"]
ignore = ["E501"]         # Ruff/formatter handles wrapping
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["sesa"]

[tool.ruff.format]
quote-style = "double"
